# Generated by Django 4.0.4 on 2022-04-17 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='img/books/default.webp', upload_to='img/books', verbose_name='Фотография книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, default=' ', max_length=1000, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Удерживайте “Control“ (или “Command“ на Mac), чтобы выбрать несколько значений.', to='catalog.genre', verbose_name='Любимые жанры'),
        ),
        migrations.AlterField(
            model_name='review',
            name='critic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Рецензия'),
        ),
    ]
