# Generated by Django 4.0.3 on 2022-04-08 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_review_book_book_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookOfDay',
            new_name='BookOfMonth',
        ),
        migrations.AlterModelOptions(
            name='bookofmonth',
            options={'ordering': ['dayOfBook'], 'verbose_name': 'Книга месяца', 'verbose_name_plural': 'Книги месяцов'},
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Select genre of this book', to='catalog.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.review'),
        ),
    ]
