# Generated by Django 4.0.3 on 2022-04-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_bookofday_bookofmonth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/books'),
        ),
        migrations.AlterField(
            model_name='bookofmonth',
            name='dayOfBook',
            field=models.DateField(verbose_name='Месяц книги'),
        ),
        migrations.AlterField(
            model_name='bookofmonth',
            name='image',
            field=models.ImageField(upload_to='images/booksOfMonth'),
        ),
    ]
