# Generated by Django 4.0.3 on 2022-04-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_book_image_alter_bookofmonth_dayofbook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookofmonth',
            options={'ordering': ['dayOfBook'], 'verbose_name': 'Книга месяца', 'verbose_name_plural': 'Книги месяца'},
        ),
    ]
