# Generated by Django 4.0.4 on 2022-04-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookofmonth',
            name='image',
            field=models.ImageField(upload_to='img/booksOfMonth'),
        ),
    ]
