# Generated by Django 4.0.4 on 2022-04-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_bookofmonth_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Ваши любимые жанры', to='catalog.genre'),
        ),
        migrations.AlterField(
            model_name='bookofmonth',
            name='image',
            field=models.ImageField(upload_to='images/booksOfMonth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, help_text='Фотография вашего профиля', upload_to='img/profiles'),
        ),
    ]
