# Generated by Django 4.0.4 on 2022-04-16 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_profile_genre_alter_bookofmonth_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.author', verbose_name='Автор книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, to='catalog.genre', verbose_name='Жанры книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/books', verbose_name='Фотография книги'),
        ),
        migrations.AlterField(
            model_name='bookofmonth',
            name='summary',
            field=models.TextField(default=' ', max_length=1000, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genre',
            field=models.ManyToManyField(blank=True, to='catalog.genre', verbose_name='Любимые жанры'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/profiles', verbose_name='Ваш аватар'),
        ),
    ]
